FROM node:21-alpine3.19

WORKDIR /usr/src/app

COPY package*.json ./
# COPY package-lock.json ./

RUN npm install

COPY . .

# Build the app
RUN npm run build

EXPOSE 3000
EXPOSE 4200

CMD ["node", "dist/main.js"]
